spring:
  application:
    name: currencymapi
  datasource:
    url: jdbc:mysql://204.13.153.225:3306/nas
    username: nas
    password: s9636h8n2455
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 204.13.153.225
    port: 6379
    password: s9636h8n2455
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间

server:
  port: 8021

eureka:
  instance:
    hostname: nasmapi
    appname: nasmapi
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://204.13.153.225:8761/eureka/

# MyBatis-Plus 配置
mybatis-plus:
  type-aliases-package: com.minyan.nascommon.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy: not_null
