spring:
  application:
    name: nascapi
  datasource:
    url: jdbc:mysql://148.135.93.196:3306/nas
    username: nas
    password: s9636h8n2455
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 148.135.93.196
    port: 6379
    password: s9636h8n2455
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间

server:
  port: 8021

eureka:
  instance:
    hostname: nascapi
    appname: nascapi
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://148.135.93.196:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.minyan.nascommon.po
