spring:
  application:
    name: nascapi
  datasource:
    url: jdbc:mysql://204.13.153.225:3306/nas
    username: nas
    password: s9636h8n2455
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis-15148.c279.us-central1-1.gce.redns.redis-cloud.com
    port: 15148
    password: MYiwHfUGi9xmw1sWYiqjkhDNabeQBIyj
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间
    timeout: 5000ms

server:
  port: 8021

eureka:
  instance:
    hostname: nascapi
    appname: nascapi
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://204.13.153.225:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.minyan.nascommon.po

currency:
  url: http://204.13.153.225:8001
